---
- name: Ignore DNS Servers from DHCP
  copy: src=templates/dhclient.conf dest=/etc/dhcp/dhclient.conf owner=root group=root mode=0644

- name: Use our DNS server
  shell: "echo 'nameserver: 172.16.2.10' >> /etc/resolvconf/resolv.conf.d/base"

- name: Ensure Resolvconf service is installed and restarted
  service:
    name: resolvconf
    state: restarted
    enabled: yes

- name: Get a new DHCP Lease without DNS information
  shell: "dhclient -r; dhclient"

- name: Template network config for eth1
  template:
    src: templates/eth1.cfg
    dest: "/etc/network/interfaces.d/eth1.cfg"
    owner: root
    group: root
    mode: 644

- name: Bring eth1 up with correct config
  shell: "ifdown eth1 && ifup eth1"