---
- hosts: all
  become: yes
  gather_facts: true
  vars:
    ip_address: 172.16.2.11

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - include: configure-dns-client.yml
